version: '3'
services:
  to-do_pgadmin:
    container_name: to-do_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
    networks:
      database:
        aliases:
          - pgadmin
    depends_on:
      - to-do_db
  to-do_web:
    container_name: to-do_web
    build:
      context: .
      dockerfile: Dockerfile_client
    tty: true
    command: cd client && npm run start
    volumes:
      - ./to_do_app:/usr/app
    ports:
      - "8000:8000"
    networks:
      backend:
    depends_on:
      - to-do_db
    environment:
      WATCHPACK_POLLING: true
  to-do_be:
    container_name: to-do_be
    build:
      context: .
      dockerfile: Dockerfile_server
    tty: true
    #command: cd server && npm run start
    volumes:
      - ./to_do_app:/usr/app
    ports:
      - "3000:3000"
    networks:
      backend:
      database:
    depends_on:
      - to-do_db
    environment:
      WATCHPACK_POLLING: true
      DATABASE_URL: postgres://postgres@to-do_db/todo_db
  to-do_db:
    container_name: to-do_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5434:5432"
    networks:
      database:

networks:
  backend:
    driver: bridge
  database:
    driver: bridge